namespace Mint.Network.Incoming;

public enum IncomingPacketID
{
    PlayerConnect = 1,
    PlayerInfo = 4,
    PlayerSlot = 5,
    PlayerRequestWorldInfo = 6,
    PlayerRequestWorldSection = 8,
    PlayerSpawn = 12,
    PlayerUpdate = 13,
    PlayerStatLife = 16,
    PlayerPvPStatus = 30,
    PlayerHealLifeEffect = 35,
    PlayerZone = 36,
    PlayerSetTalkNpc = 40,
    PlayerItemAnimation = 41,
    PlayerStatMana = 42,
    PlayerHealManaEffect = 43,
    PlayerSetTeam = 45,
    PlayerSpawnSyncOthers = 49,
    PlayerBuffsID = 50,
    PlayerBuffAdd = 55,
    PlayerCreateSound = 58,
    PlayerDodge = 62,
    PlayerAndNpcTeleport = 65,
    PlayerHealStatLife = 66,
    PlayerUUID = 68,
    PlayerTeleportViaItem = 73,
    PlayerFinishedAnglerQuest = 75,
    PlayerGolferAndAnglerData = 76,
    PlayerStealth = 84,
    PlayerSetMinionTargetPoint = 99,
    PlayerSetMinionTargetNPC = 115,
    PlayerTeleportToPortal = 100,
    PlayerNebulaLevelUp = 102,
    PlayerSendHurt = 117,
    PlayerSendKill = 118,
    PlayerEmoteBubble = 120,
    PlayerSyncPickTile = 125,
    PlayerLuckFactors = 134,
    PlayerLucyMessage = 141,
    PlayerPiggyBankVoidLens = 142,
    PlayerSwitchLoadout = 147,

    WorldTileInteraction = 17,
    WorldPaintTile = 63,
    WorldPaintWall = 64,
    WorldPlaceTileV2 = 79,
    WorldTileEntityPlace = 87,
    WorldTileEntityPlaceItemFrame = 89,
    WorldDoorOpen = 19,
    WorldTileRectangle = 20,
    WorldSetLiquidOutdated = 48,
    WorldTileAnimation = 77,
    WorldTileToggleGemLock = 105,
    WorldTreeGrowFX = 112,
    WorldTileEntityDisplayDollItem = 121,
    WorldTileEntityInteractionAchor = 122,
    WorldTileEntityPlaceItemRack = 123,
    WorldTileEntityHatRackItem = 121,
    WorldTileEntityFoodPlatterPlace = 121,

    GolfPutBallInCup = 128,

    ItemDropV1 = 21,
    ItemDropV2 = 90,
    ItemDropShimmered = 145,
    ItemDropCannotBeTakenByMonsters = 148,
    ItemOwner = 22,
    ItemDropModifiedItem = 88,
    ItemShimmerEffect = 146,

    NpcStrike = 24,
    NpcAddBuff = 53,
    NpcSetName = 56,
    NpcTownSetHome = 60,
    NpcCatch = 70,
    NpcRelease = 71,
    NpcTravellerShop = 72,
    NpcExtraValue = 92,
    NpcSpawnFromFishing = 130,
    NpcCavernMonsterType = 136,
    NpcRequestBuffRemoval = 137,
    NpcTransformSlime = 140,
    NpcDryadStardewAnimation = 144,

    ProjectileUpdate = 27,
    ProjectileStrikeNpc = 28,
    ProjectileDestroy = 29,
    ProjectileKillMy = 95,

    ChestUseTrap = 31,
    ChestSetItem = 32,
    ChestName = 33,
    ChestPlaceOrDestroy = 34,
    ChestAndDoorUnlock = 52,
    ChestGetNameIn = 69,
    ChestPlaceItem = 85,

    PasswordCheck = 38,

    SignRead = 46,
    SignSetText = 47,

    EventsBossesNpcsV1 = 51,
    EventsBossesNpcsV2 = 61,
    EventsReportProgress = 78,
    EventsToggleParty = 111,
    EventsDD2SummonCrystal = 113,
    EventsDD2SkipWaitTime = 143,

    WiringHitSwitch = 59,
    WiringMassTileOperation = 109,
    WiringConsumeWires = 110,

    NetEmoteBubble = 91
}