global using TPlayer = Terraria.Player;
global using Net = Terraria.NetMessage;
global using Mint.Core;
global using Mint.Assemblies;
global using Mint.Assemblies.Modules;
global using Mint.Network;
global using Mint.Server;
global using Mint.Server.Auth;
global using Mint.Server.Commands;
global using Mint.Server.Chat;
global using Mint.Server.Hooks;
global using Mint.DataStorages;
global using Mint.Network.Incoming;
global using Mint.Network.Outcoming;
global using Mint.Localization;
global using Serilog;
global using ModSend = On.Terraria.NetMessage;
global using ModGet = On.Terraria.MessageBuffer;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;